import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { CloudProvider } from '../../providers/enums/cloud-provider.enum';

export class SSHKeyDto {
  @ApiProperty({ description: 'SSH key unique identifier' })
  id: string;

  @ApiProperty({ description: 'SSH key name/label' })
  name: string;

  @ApiProperty({ description: 'SSH public key content' })
  publicKey: string;

  @ApiProperty({ description: 'SSH key fingerprint' })
  fingerprint: string;

  @ApiProperty({ description: 'SSH key type (rsa, ed25519, etc.)' })
  type: string;

  @ApiProperty({ description: 'Key creation date' })
  createdAt: Date;

  @ApiPropertyOptional({ description: 'Key last update date' })
  updatedAt?: Date;

  @ApiProperty({
    description: 'Key source',
    enum: ['local', ...Object.values(CloudProvider)],
    example: 'local',
  })
  source?: 'local' | CloudProvider;

  @ApiPropertyOptional({
    description: 'Whether this key was synced from a provider',
    default: false,
  })
  syncedFromProvider?: boolean;

  @ApiPropertyOptional({
    description: 'Provider where this key is also available',
    enum: CloudProvider,
  })
  availableOnProvider?: CloudProvider;

  @ApiPropertyOptional({
    description: 'Provider-specific key ID (if synced)',
  })
  providerKeyId?: string;

  @ApiProperty({
    description: 'Whether the SSH key is currently active',
    default: true,
  })
  isActive: boolean;

  @ApiProperty({
    description:
      'Whether this SSH key was automatically generated by the system',
    default: false,
  })
  autoGenerated: boolean;

  @ApiPropertyOptional({
    description: 'Last time this key was used (if available)',
  })
  lastUsed?: Date;

  @ApiPropertyOptional({
    description: 'Key-value pairs for tagging. Values can be strings or arrays',
    example: {
      'cluster-id': ['k3s-prod-eu-001', 'k3s-prod-eu-002'],
      'cluster-node-id': 'node-worker-02',
      roles: ['master', 'worker'],
    },
    required: false,
  })
  tags?: Record<string, string | string[]>;

  @ApiPropertyOptional({
    description: 'Mapping of cloud provider to provider-specific SSH key IDs',
    example: {
      HETZNER: '12345',
      CONTABO: 'abc-def',
    },
    required: false,
  })
  providerKeyMappings?: Record<string, string>;

  @ApiPropertyOptional({
    description:
      'Provider sync errors, present only when one or more providers failed to sync. ' +
      'The key was created locally and synced successfully to providers NOT listed here.',
    example: { SCALEWAY: 'Request failed with status code 409' },
  })
  syncErrors?: Partial<Record<CloudProvider, string>>;
}
